export const ActionTypes = {
    // user
    USER_REGISTER_PENDING: "USER_REGISTER_PENDING",
    USER_LOGIN_PENDING: "USER_LOGIN_PENDING",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

    //products
    SET_PRODUCTS: "SET_PRODUCTS",
    CREATE_PRODUCTS: "CREATE_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
    DELETE_PRODUCTS: "DELETE_PRODUCTS",
    ADD_PRODUCTS_PENDING: "ADD_PRODUCTS_PENDING",
    GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    UPDATE_USER: "UPDATE_USER",
    GET_PRODUCT_PENDING: "GET_PRODUCT_PENDING",
}